### ISSUE TITLE
Can't import it in sublime

### ISSUE THREAD

**Issue by miladd10** [Superxwolf/Nakama-Sublime#1]
It seems there is no "Nakama Autocomplete" Package in sublime and also I cant import it manually because when I  put the folder in my package folder \AppData\Roaming\Sublime Text 3\Packages
it doesn't work!

**Comment by Superxwolf** [comment]
I'm still in the middle of getting the plugin on Package Control, it's not a quick process.

The plugin should work by just dropping the repository inside a folder in the package folder. If you press ``` Ctrl + ` ``` it'll pull up the sublime text console. You can check there if it's loading the plugin or it's displaying any errors. If it shows an error please paste it here so I can verify.

**Comment by miladd10** [comment]
`DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Milad/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Milad/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Milad/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.601948
startup time: 0.681948
first paint time: 0.687948
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin LuaAutocomplete.locals
reloading plugin LuaAutocomplete.LuaAutocomplete
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control`
_**reloading plugin Nakama-Sublime-master.Nakama
reloading plugin Nakama-Sublime-master.Nakama_doc_fetch
reloading plugin Nakama-Sublime-master.Nakama_realtime
reloading plugin Nakama-Sublime-master.Nakama_rt_doc_fetch**_
`plugins loaded
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages
reloading settings Packages/User/Preferences.sublime-settings`

this is what in my console it seems plugins loaded (but in my package setting nothing is added )
`"installed_packages":
	[
		"LuaAutocomplete",
		"LuaExtended",
		"Package Control"
	]`

when I use 
`local nk = require("nakama")`
in my code there is no auto completion for nk ... my question is would I put nakama's libs some where in sublime package folder?

**Comment by Superxwolf** [comment]
Seems like the problem was compatability with another Lua syntax plugin. I just pushed a fix for that, please try it out and let me know if it all works out for you.

The plugin is self-sustained and does not require any aditional files to work.

**Comment by miladd10** [comment]
Alright! yes you are right cause when I removed LuaAutocomplete and LuaExtended packages it perfectly worked! 
thanks for your reply by the way and hope to see the plugin on Package Control soon :)

**Comment by Superxwolf** [comment]
Thanks, hope it helps you make your great game faster!
